### ISSUE TITLE
Publishing to Hex

### ISSUE THREAD

**Issue by sashman** [glasnoster/eliver#4]
Hey, was just glancing at your TODO, am I correct in thinking you're looking for an automated way to publish to hex after a release?

**Comment by lm-pretorius** [comment]
Hey @sashman,

That was the thinking when I first wrote the readme, but I've convinced myself that an explicit `mix hex.publish` is probably better.

What do you think?

**Comment by lm-pretorius** [comment]
Mmm, maybe a prompt asking "Release to Hex? [Y/n]" would be nice. :)

**Comment by sashman** [comment]
Hey @glasnoster, IMHO I'd like to see the version bumping and publishing to hex as two decoupled flows. Some people would potentially want to manually bump the version and leave the publishing to be done automatically via CI.

For example, at the end of your CI run: 

```
#!/bin/sh

echo "$HEX_USER\n$HEX_PASSWORD" | mix hex.user auth
echo "y\n$HEX_PASSWORD" | mix hex.publish
```

As far as I know, at the moment there isn't a nice way to automatically trigger `mix hex.publish`, so you have to pipe into standard in. `$HEX_USER` and `$HEX_PASSWORD` would be stored as secrets. Also, I **think** hex publish doesn't update the package on hex if the version has not changed, so you should be safe to run this on every CI run?

**Comment by lm-pretorius** [comment]
I agree. Leaving version bumping and publishing as two separate flows is definitely better.

I'll update the readme.
