### ISSUE TITLE
Does this tool provide anything that needs to be in `prod`?

### ISSUE THREAD

**Issue by NobbZ** [glasnoster/eliver#6]
The README.md suggests to put this as a `prod`-dependency, but it does not seem to suggest to use any function or macro defined in this package, but instead solely relies on the standard library in the suggested changes to `mix.exs`.

The only thing (it seems) that is userfacing is the mix task to bump the version. This bump is usually done by a developer of any kind in an interactive entvironment.

Therefore I wanted to ask, if this is actually necessary as a prod dependency or if it can be safely used in `dev`, and if the README could be changed accordingly.

**Comment by lm-pretorius** [comment]
Hi @NobbZ!

Apologies for the late reply. For some reason I did not get notified about the issue you created.

You're right, this is a development dependency.
I'll change the documentation accordingly.

Thanks for bringing it up!
